---
layout: post
title:  "Directory Services (Exposition)"
date:   2026-01-14 23:15:37 +0300
categories: ActiveDirectory
---
New year, renewed drive to post. Trying a different writing approach this time. Enjoy!

You have heard of Microsoft Active Directory, but why is it called a "directory"? And why is the L in its LDAP protocol "lightweight"? You'll have to get comfortable because we're taking a long trip - plus detours - in the short history of Information Technology and the patterns it follows (keep in mind I'm not the best historian). Innovations in software usually take inspiration from inventions that were already useful in the physical world, and these inventions usually come into being to overcome limitations. Over the years, these innovations may become common knowledge, they may become obsolete and forgotten, or they may even become vestiges of what they once were or otherwise get adapted to answer newer necessities, making its original story esoteric knowledge!

Let's start with phones. As the number of land lines increased, the complexity of phone networks increased, making one-to-one direct phone connections no longer feasible, thus came the first phone exchanges that had switchboards which were manually operated by phone operators. Subscribers to the phone service were initially identified by their name, so one had to inform the operator about who they wanted to call. Then the idea of identifying a subscriber by a short unique number came. Then as the number of telephone exchanges increased, the idea of identifying an exchange by a unique name familiar to the locals also appeared, and the first few letters of that name would become part of the "number" you're trying to reach, assuming it subscribed to another provider. Eventually switchboards got automated rendering operators redundant, making knowing the correct phone number even more important. This was also around the time the rotary phone dial started having letters added above its numbers. (Detour: Each digit of a rotary phone sent a number of "pulses" equal to the digit being dialed, this made dialing numbers with higher digits slower. Newer digital phones had the "tones" that we are familiar with, which both unified and shortened dial times. Some digital phones - and also modems - had a setting to change between pulse and tone modes for backwards compatibility with older providers).

That's when the use of books showing the numbers of all subscribers of an area became more common. These phone "directories" could be found within phone booths or sold separately. They also had white pages for residential entries, and yellow pages for paid entries - essentially ads for business - showing both numbers and addresses, but phone directories weren't the first type of directory to be made; city directories listing businesses were already a thing before the invention of phones, however we'll end up following a long chain of what-inspired-what if we talked about those.

These physical directories brought a wealth of information, but printed paper cannot be updated easily. This is why the notion of digitized directories was the next logical step, but phones weren't the main catalyst here, it was postal mail! In parallel to phones, we also had paper mail, that got partially superseded by telegrams, then it finally became obsolete thanks to electronic mail (e-mail), but a challenge for e-mail was how to handle the digital version of "addresses" so that e-mails can go through the digital version of the "post office" in a standardized way. That's when some brilliant people invented the X.400 standard, which had some features that were ahead of its time, but unfortunately this was a point of history where many competing standards for different things were being made, some even liked to call them "wars" (Detour: Anyone old enough to remember the Betacam / VHS video cassette wars? Or even the PAL/NTSC video standards? At least I'm sure we have some who know the pain of 110v vs 220v and the smell of burnt appliances!), and computer networks were no exception. Designers of X.400 put a lot of their early efforts on the OSI protocols as they were meant to become the universal standard of communications, but OSI was incompatible with the already existing TCP/IP, which at the time was a suite of protocols designed for the much smaller ARPANET (the precursor to the Internet). We now know who won that "war", and the only part of OSI that is still relevant is its 7-layers model of networking.

This is enough for the exposition part of our story/article. Next time we'll talk about the X.400 e-mail standard, its relation to the X.500 directory services standard, and how it lead to LDAP.
